Adapted the source code to Windows file-system compatible structure, using our internal automatation script. Then manually cherry-picked all commits made for blueCFD-Core 2016, from the blueCFD-Core-4.x branch, i.e. excluding all commits that were from the OpenFOAM-4.x branch.

diff --git a/wmake/scripts/makeVersionResourceFile b/wmake/scripts/makeVersionResourceFile
--- a/wmake/scripts/makeVersionResourceFile
+++ b/wmake/scripts/makeVersionResourceFile
@@ -1,14 +1,10 @@
 #!/bin/sh
 #------------------------------------------------------------------------------
-# =========                 |
-# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
-#  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2011 OpenFOAM Foundation
-#    \\/     M anipulation  |
-#-------------------------------------------------------------------------------
 # 2014-02-21 blueCAPE Lda: Modifications for blueCFD-Core 2.3-1
-# 2016-03-15 blueCAPE Lda: Modifications for blueCFD-Core 2016-1
-# 2016-07-22 blueCAPE Lda: More modifications for blueCFD-Core 2016-1
+# 2016-03-15 blueCAPE Lda: Modifications for blueCFD-Core 2.3-2 and 2016-1
+# 2016-07-xx blueCAPE Lda: More modifications for blueCFD-Core 2016-1
+# 2016-10-16/23 blueCAPE Lda: More modifications for blueCFD-Core 2016-2
+# 2016-12-07 blueCAPE Lda: More modifications for blueCFD-Core 2016-2
 #------------------------------------------------------------------------------
 # License
 #     This file is a derivative work of OpenFOAM.
@@ -27,17 +23,25 @@
 #     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
 #
 # Modifications
-#     This file has been modified by blueCAPE's unofficial mingw patches for
+#     This file has been created by blueCAPE's unofficial mingw patches for
 #     OpenFOAM.
 #     For more information about these patches, visit:
 #         http://bluecfd.com/Core
 #
 #     Modifications made:
-#        - Derived from the patches for blueCFD 2.1 and 2.2.
-#        - Added the ability to build localized builds for each MPI toolbox.
-#        - Added ability to build the resource files for embedding into the
-#          binaries, therefore allowing us to add version information to the
-#          binaries for Windows to see.
+#        - Originally derived from the patches for blueCFD 2.1 and 2.2, which
+#          were applied to the file makeDerivedFiles.
+#        - This script makeVersionResourceFile was later created for
+#          blueCFD-Core 2.3-2 and 2016-1, based on the original modifications.
+#        - This script has the ability to build the resource files for
+#          embedding them in binaries, therefore allowing us to add version
+#          information to the binaries for Windows to see.
+#        - Cleaned up the code a bit and made the script able to update the dep
+#          file and only update the sourcesFile.
+#        - Split this script into three:
+#          - makeVersionResourceFile
+#          - makeVersionResourceDepFile
+#          - makeVersionResourceSListFile
 #
 # Script
 #     makeVersionResourceFile
@@ -47,36 +51,35 @@
 #
 #------------------------------------------------------------------------------
 
-# Provided by MakefileFiles
+# Provided by makefiles/files
 OBJECTS_DIR=$1
 VERSIONFILE=$2
-SFILES=$3
-VARS=$4
+VARS=$3
 
 # Change to the $OBJECTS_DIR directory
-cd "$OBJECTS_DIR" 2>/dev/null || {
-    echo "Could not change to directory '$OBJECTS_DIR'" 1>&2
+if [ ! -d "$OBJECTS_DIR" ]
+then
+    echo "Could not use the directory '$OBJECTS_DIR'" 1>&2
     exit 1
-}
-
-# Special preparations for MinGW builds
-TIS_MinGW=0
-if [ -e "$FOAM_SRC/OSspecific/$WM_OSTYPE/res/OFversion_template.rc" ]; then
-    TIS_MinGW=1
-    cp "$FOAM_SRC/OSspecific/$WM_OSTYPE/res/OFversion_template.rc" tmpver.rc
 fi
 
-if [ $TIS_MinGW -eq 1 ]; then
+# Special preparations for MinGW builds
+if [ -e "$FOAM_SRC/OSspecific/$WM_OSTYPE/res/OFversion_template.rc" ]
+then
+    cp "$FOAM_SRC/OSspecific/$WM_OSTYPE/res/OFversion_template.rc" tmpver.rc
+
     #Extract the binary name
     MGW_EXENAME=$(grep -e "^EXE =" $VARS)
     MGW_LIBNAME=$(grep -e "^LIB =" $VARS)
     MGW_FINALNAME="NONAME"
 
-    if [ -n "$MGW_EXENAME" ]; then
+    if [ -n "$MGW_EXENAME" ]
+    then
         MGW_FINALNAME=$(echo $MGW_EXENAME | sed -e 's=.*/==').exe
     fi
 
-    if [ -n "$MGW_LIBNAME" ]; then
+    if [ -n "$MGW_LIBNAME" ]
+    then
         MGW_FINALNAME=$(echo $MGW_LIBNAME | sed -e 's=.*/==').dll
     fi
 
@@ -87,39 +90,14 @@ if [ $TIS_MinGW -eq 1 ]; then
     sed -e 's=2\.0\.\0\.0='$MGW_OFversion'=g' \
         -e 's=tmpintname='$MGW_FINALNAME'=' \
         -e 's=tmporigname='$MGW_FINALNAME'=' \
-        tmpver.rc > $VERSIONFILE
+        tmpver.rc > "${VERSIONFILE}"
 
     #clean up
     unset MGW_OFversion MGW_EXENAME MGW_LIBNAME MGW_FINALNAME
     rm tmpver.rc
 
 else
-
     exit 1
 fi
-
-# Plug in the version resource file for being compiled along
-DEPFILE=${VERSIONFILE}.dep
-FILE_NAMEwEXT=${VERSIONFILE##*/}
-FILE_NAME=${FILE_NAMEwEXT%%.rc}
-
-echo "$FILE_NAMEwEXT" > files.$$
-
-# Update sourceFiles
-sed -i -e '$s/$/\\/' $SFILES
-
-cat files.$$ >> $SFILES
-
-# Create custom made dep file
-touch ${VERSIONFILE}.dep
-echo '$(OBJECTS_DIR)/'$FILE_NAMEwEXT'.dep: $(OBJECTS_DIR)/'$FILE_NAMEwEXT \
-     >> $DEPFILE
-echo '' >> $DEPFILE
-echo '$(OBJECTS_DIR)/'$FILE_NAME'.o : $(OBJECTS_DIR)/'$FILE_NAMEwEXT \
-     >> $DEPFILE
-echo '	$(rctoo)' >> $DEPFILE
-
-# Remove temporary file
-rm files.$$
 
 #------------------------------------------------------------------------------
